// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package positions

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE0c3566dDecodeSemInternalPositions(in *jlexer.Lexer, out *Position) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "keyword":
			out.Keyword = string(in.String())
		case "position":
			out.Position = uint64(in.Uint64())
		case "url":
			out.Url = string(in.String())
		case "volume":
			out.Volume = uint64(in.Uint64())
		case "results":
			out.Results = uint64(in.Uint64())
		case "cpc":
			out.Cpc = float64(in.Float64())
		case "updated":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Updated).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE0c3566dEncodeSemInternalPositions(out *jwriter.Writer, in Position) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"keyword\":"
		out.RawString(prefix[1:])
		out.String(string(in.Keyword))
	}
	{
		const prefix string = ",\"position\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Position))
	}
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix)
		out.String(string(in.Url))
	}
	{
		const prefix string = ",\"volume\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Volume))
	}
	{
		const prefix string = ",\"results\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Results))
	}
	{
		const prefix string = ",\"cpc\":"
		out.RawString(prefix)
		out.Float64(float64(in.Cpc))
	}
	{
		const prefix string = ",\"updated\":"
		out.RawString(prefix)
		out.Raw((in.Updated).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Position) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE0c3566dEncodeSemInternalPositions(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Position) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE0c3566dEncodeSemInternalPositions(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Position) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE0c3566dDecodeSemInternalPositions(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Position) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE0c3566dDecodeSemInternalPositions(l, v)
}
